### PR TITLE
fix typo and make it compile with SSL 1.1.0

### PR DESCRIPTION
**Pull request by alteholz**

### CODE REVIEW

**Comment by Chocobo1** [comment]
With this change, I still got error when building:
```
libtool: link: gcc -I../../src -I../../src/gen -I../../src/lib -I../../src/stat -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DHAVE_SSL -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z -Wl,relro -o httperf httperf.o object.o call.o conn.o sess.o core.o localevent.o http.o timer.o  gen/libgen.a lib/libutil.a stat/libstat.a -lssl -lcrypto -lm
httperf.o: In function `main':
httperf.c:(.text.startup+0x5bb): undefined reference to `SSLeay_add_all_algorithms'
httperf.c:(.text.startup+0x13cb): undefined reference to `SSLv2_client_method'
```
and I found this: https://github.com/openssl/openssl/issues/1543

**Comment by davidlt** [comment]
Based on changes you probably need something like below. Compiles fine on Fedora 26 with OpenSSL 1.1.0f, but did not yet tested.

```
diff --git a/src/core.c b/src/core.c
index bb4929e..a6ba6f8 100755
--- a/src/core.c
+++ b/src/core.c
@@ -1035,9 +1035,9 @@ core_ssl_connect(Conn * s)
 				"suites!\n");
 		else
 			fprintf(stderr,
-				"core_ssl_connect: cipher=%s, valid=%d, id=%lu\n",
-				ssl_cipher->name, ssl_cipher->valid,
-				ssl_cipher->id);
+				"core_ssl_connect: cipher=%s, id=%lu\n",
+				SSL_CIPHER_get_name(ssl_cipher),
+				SSL_CIPHER_get_id(ssl_cipher));
 	}
 
 	arg.l = 0;
diff --git a/src/httperf.c b/src/httperf.c
index a7beb31..b9f5a7b 100755
--- a/src/httperf.c
+++ b/src/httperf.c
@@ -1001,27 +1001,12 @@ main(int argc, char **argv)
 		if (param.port < 0)
 			param.port = 443;
 
-                SSL_library_init ();
+                SSL_library_init (); // Redundant with the below?
 		SSL_load_error_strings ();
-                SSLeay_add_all_algorithms ();
-		SSLeay_add_ssl_algorithms ();
+                OpenSSL_add_all_algorithms ();
+		//OpenSSL_add_ssl_algorithms ();
 
-		switch (param.ssl_protocol)
-                {
-                    /* 0/auto for SSLv23 */
-                    case 0: ssl_ctx = SSL_CTX_new (SSLv23_client_method ()); break;
-#ifndef OPENSSL_NO_SSL2
-                    /* 2/SSLv2 */
-                    case 2: ssl_ctx = SSL_CTX_new (SSLv2_client_method ()); break;
-#endif
-#ifndef OPENSSL_NO_SSL3
-                    /* 3/SSLv3 */
-                    case 3: ssl_ctx = SSL_CTX_new (SSLv3_client_method ()); break;
-#endif
-                    /* 4/TLSv1 */
-                    case 4: ssl_ctx = SSL_CTX_new (TLSv1_client_method ()); break;
-                }
-      
+                ssl_ctx = SSL_CTX_new (TLS_client_method ());
 		if (!ssl_ctx) {
 			ERR_print_errors_fp(stderr);
 			exit(-1);
diff --git a/src/timer.c b/src/timer.c
index 77a2367..558bb91 100755
--- a/src/timer.c
+++ b/src/timer.c
@@ -31,6 +31,7 @@
 
 #include "config.h"
 
+#include <string.h>
 #include <assert.h>
 #include <errno.h>
 #include <stdio.h>
```

**Comment by erikarn** [comment]
done, thanks!

**Comment by Reylak** [comment]
Still does not build with OpenSSL 1.1.0g, because @davidlt's patch is needed (except for "core.c").
