### ISSUE TITLE
error: ‘SSL_OP_NO_TLSv1_3’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by xiaoyuit** [httperf/httperf#54]
I compiled to find this error, how can I solve it：

`
make  all-recursive
make[1]: Entering directory `/vagrant/packages/httperf-master'
Making all in src
make[2]: Entering directory `/vagrant/packages/httperf-master/src'
Making all in gen
make[3]: Entering directory `/vagrant/packages/httperf-master/src/gen'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/vagrant/packages/httperf-master/src/gen'
Making all in lib
make[3]: Entering directory `/vagrant/packages/httperf-master/src/lib'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/vagrant/packages/httperf-master/src/lib'
Making all in stat
make[3]: Entering directory `/vagrant/packages/httperf-master/src/stat'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/vagrant/packages/httperf-master/src/stat'
make[3]: Entering directory `/vagrant/packages/httperf-master/src'
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..    -I. -I./gen -I./lib -I./stat -g -O2 -DHAVE_SSL -MT httperf.o -MD -MP -MF .deps/httperf.Tpo -c -o httperf.o httperf.c
httperf.c: In function ‘main’:
httperf.c:1032:126: error: ‘SSL_OP_NO_TLSv1_3’ undeclared (first use in this function)
                     SSL_CTX_set_options(ssl_ctx, SSL_OP_NO_SSLv3 | SSL_OP_NO_TLSv1 | SSL_OP_NO_TLSv1_1 | SSL_OP_NO_TLSv1_2 | SSL_OP_NO_TLSv1_3);
                                                                                                                              ^
httperf.c:1032:126: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [httperf.o] Error 1
make[3]: Leaving directory `/vagrant/packages/httperf-master/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/vagrant/packages/httperf-master/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/vagrant/packages/httperf-master'
make: *** [all] Error 2
`

**Comment by erikarn** [comment]
Hi,

This looks like it was introduced recently. Will have to go see why this
happened!


-a

**Comment by rpinz** [comment]
This issue was introduced by commit #53.  A potential interim solution could look like this...

```
diff --git a/src/httperf.c b/src/httperf.c
index e0abd51..63180fa 100755
--- a/src/httperf.c
+++ b/src/httperf.c
@@ -1029,7 +1029,11 @@ main(int argc, char **argv)
                     case 2: 
 #if (OPENSSL_VERSION_NUMBER >= 0x10100000L)
                     ssl_ctx = SSL_CTX_new (TLS_client_method ());
+#if (OPENSSL_VERSION_NUMBER >= 0x10101000L)
                     SSL_CTX_set_options(ssl_ctx, SSL_OP_NO_SSLv3 | SSL_OP_NO_TLSv1 | SSL_OP_NO_TLSv1_1 | SSL_OP_NO_TLSv1_2 | SSL_OP_NO_TLSv1_3);
+#else
+                    SSL_CTX_set_options(ssl_ctx, SSL_OP_NO_SSLv3 | SSL_OP_NO_TLSv1 | SSL_OP_NO_TLSv1_1 | SSL_OP_NO_TLSv1_2);
+#endif
 break;
 #else
                     ssl_ctx = SSL_CTX_new (SSLv2_client_method ()); break;
@@ -1041,7 +1045,11 @@ break;
                     case 3: 
 #if (OPENSSL_VERSION_NUMBER >= 0x10100000L)
                     ssl_ctx = SSL_CTX_new (TLS_client_method ());
+#if (OPENSSL_VERSION_NUMBER >= 0x10101000L)
                     SSL_CTX_set_options(ssl_ctx, SSL_OP_NO_SSLv2 | SSL_OP_NO_TLSv1 | SSL_OP_NO_TLSv1_1 | SSL_OP_NO_TLSv1_2 | SSL_OP_NO_TLSv1_3);
+#else
+                    SSL_CTX_set_options(ssl_ctx, SSL_OP_NO_SSLv2 | SSL_OP_NO_TLSv1 | SSL_OP_NO_TLSv1_1 | SSL_OP_NO_TLSv1_2);
+#endif
 break;
 #else
                     ssl_ctx = SSL_CTX_new (SSLv3_client_method ()); break;
```

**Comment by muzaffar1331** [comment]
My apologies. This issue happened because it was assumed that TLS 1.3 would be available in versions of OpenSSL newer than 1.0.1, which was not the case: TLS 1.3 will be available as from version 1.1.1.
Fixed it in a new commit by now checking for OPENSSL_VERSION_NUMBER >= 0x10101000L as pointed out by @rpinz
