### ISSUE TITLE
Incompatible with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by eribertomota** [httperf/httperf#45]
Hi,

The httperf doesn't build with new OpenSSL 1.1.0. This issue was reported in Debian here[1].

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828343

The error message is:

-----------------------------------------------------
f/httperf-0.9.0=. -fPIE -fstack-protector-strong -Wformat -Werror=format-security -DHAVE_SSL -c -o core.o core.c
core.c: In function ‘core_ssl_connect’:
core.c:803:18: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       ssl_cipher = SSL_get_current_cipher (s->ssl);
                  ^
core.c:809:14: error: dereferencing pointer to incomplete type ‘SSL_CIPHER {aka struct ssl_cipher_st}’
    ssl_cipher->name, ssl_cipher->valid, ssl_cipher->id);
              ^~
Makefile:466: recipe for target 'core.o' failed
make[4]: *** [core.o] Error 1
-----------------------------------------------------

This issue will break httperf in Debian if not fixed up to middle of November 2016.

Thanks a lot in advance.

Regards,

Eriberto

**Comment by davidlt** [comment]
See https://github.com/httperf/httperf/pull/48

**Comment by Reylak** [comment]
@davidlt's [patch](https://github.com/httperf/httperf/pull/48?_pjax=%23js-repo-pjax-container#issuecomment-317412507) in #48 has not been integrated, and the build still fails with OpenSSL 1.1.0g.
